name: conv_tasnet_training
jobs:
  data:
    sampling_rate: 16000
    wav_root_path: /Users/atsushi/Documents/Workspace/Github/asp_tools/data/LibriSpeech/
    json_train_path: /Users/atsushi/Documents/Workspace/Github/asp_tools/data/LibriSpeech/settings/dev-clean/valid-2mix.json
    json_valid_path: /Users/atsushi/Documents/Workspace/Github/asp_tools/data/LibriSpeech/settings/dev-clean/valid-2mix.json


  model:
    name: conv_tasnet
    params:
      task: train
      n_basis: 8
      kernel_size: 16
      stride: # None
      enc_basis: trainable
      dec_basis: trainable
      enc_nonlinear: # None
      sep_hidden_channels: 128
      sep_bottleneck_channels: 128
      sep_skip_channels: 128
      sep_kernel_size: 3
      sep_num_blocks: 3
      sep_num_layers: 8
      dilated: True
      separable: True
      sep_nonlinear: prelu
      sep_norm: True
      mask_nonlinear: sigmoid
      causal: True
      n_sources: 2

  training:
    n_sources: 2
    n_epoch: 100
    n_batch: 16
    lr: 1e-4
    num_workers: 0
    pin_memory: False
    use_cuda: False
    overwrite: True
    max_norm: True
    last_model_path: /tmp/model.pth
    best_model_path: /tmp/best_model.pth

  optim:
    name: Adam
    params:
      lr: 1e-4
      # betas: [0.9, 0.98]
      # eps: 1e-08
      weight_decay: 0

  criterion:
    name: sisdr
